# Bicep template deployment 

trigger: none

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Deploy
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'IACAssessment'
          subscriptionId: '23099c6b-b4cc-4da9-85fb-3e8048e47804'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'myResourceGroup'
          location: 'East US'
          templateLocation: 'Linked artifact'
          csmFile: 'IAC_Code/main.bicep'
          csmParametersFile: 'IAC_Code/parameters.json'
          deploymentMode: 'Incremental'
